### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/donation#12]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] donation_direct_debit
- [ ] donation_tax_receipt
- [ ] donation_recurring
- [ ] donation_thanks
- [ ] donation
- [ ] donation_bank_statement
- [ ] donation_recurring_tax_receipt

**Comment by alexis-via** [comment]
All modules have been ported to v9, so I close this ticket.
