### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/donation#23]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] donation - By @alexis-via - #24 
- [x] donation_bank_statement - By @alexis-via - #24 
- [x] donation_direct_debit - By @alexis-via - #24 
- [x] donation_recurring - By @alexis-via - #24 
- [x] donation_recurring_tax_receipt - By @alexis-via - #24 
- [x] donation_tax_receipt - By @alexis-via - #24 
- [x] donation_thanks - By @alexis-via - #24

**Comment by pedrobaeza** [comment]
Closing as all modules has been merged in the Alexis' mega pack PR 😆
