### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/donation#28]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] donation - By @nikul-serpentcs - #46 
- [x] donation_bank_statement - By @tbaden - #55 
- [x] donation_base - By @nikul-serpentcs - #45 
- [x] donation_direct_debit - By @tbaden - #53 
- [x] donation_recurring - By @nikul-serpentcs - #48 
- [x] donation_sale - By @nikul-serpentcs - #47 
- [ ] donation_thanks - By @tbaden - #54

**Comment by alexis-via** [comment]
FYI, I don't plan to work on v11 for my odoo projects, so I probably won't port the donation modules to v11 myself. If you need them for v11, feel free to port them and ask me questions if needed.

**Comment by nikul-serpentcs** [comment]
@pedrobaeza donation_base => https://github.com/OCA/donation/pull/45

**Comment by nikul-serpentcs** [comment]
@pedrobaeza donation => #46

**Comment by nikul-serpentcs** [comment]
@pedrobaeza  donation_sale => #47

**Comment by nikul-serpentcs** [comment]
@pedrobaeza donation_recurring => #48

**Comment by tbaden** [comment]
@OCA-git-bot donation_direct_debit

**Comment by tbaden** [comment]
@OCA-git-bot donation_direct_debit https://github.com/OCA/donation/pull/53

**Comment by tbaden** [comment]
@pedrobaeza donation_thanks https://github.com/OCA/donation/pull/54

**Comment by tbaden** [comment]
@pedrobaeza donation_bank_payment https://github.com/OCA/donation/pull/55
